spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacydb
    username: root
    password: welcome1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
      
#spublic repo      
store:
  storeName: Medplus
  storeNo: 200
  managerName: seth
  openingHours: 10
  closingHours: 23      